# Generated by Django 4.2.4 on 2023-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='نام دستخ بندی')),
                ('image', models.ImageField(upload_to='', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver_name', models.CharField(max_length=199, verbose_name='نام تحویل گیرنده')),
                ('reciver_address', models.TextField(verbose_name='آدرس تحویل گیرندخ')),
                ('reciver_phone', models.TextField()),
                ('order_full_price', models.PositiveBigIntegerField(verbose_name='قیمت کل سفارش')),
                ('order_date', models.DateField(auto_now=True, verbose_name=' تاریخ سفارش ')),
                ('order_delivery_date', models.DateTimeField(verbose_name='تاریح تحویل سفارش')),
                ('status', models.CharField(choices=[('1', 'سبد خرید'), ('2', 'در انتظار پرداخت'), ('3', 'در انتظار تایید'), ('4', 'در حال ارسال'), ('5', 'تحویل شد'), ('6', 'انصراف داده شد')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('image', models.ImageField(upload_to='')),
                ('discription', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('discount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('special', models.BooleanField()),
            ],
        ),
    ]
