# Generated by Django 4.2.4 on 2023-09-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': ' سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصول ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=99, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciver_address',
            field=models.TextField(verbose_name='آدرس تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciver_phone',
            field=models.CharField(max_length=11, verbose_name='شماره تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'سبد خرید'), ('2', 'در انتظار پرداخت'), ('3', 'در انتظار تایید'), ('4', 'در حال ارسال'), ('5', 'تحویل شد'), ('6', 'انصراف داده شد')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تخفیف محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(verbose_name='توضیحات محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=99, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='special',
            field=models.BooleanField(verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='موجودی محصول'),
        ),
    ]
